services:
  postgres:
    image: postgres:16
    container_name: techtest-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techtest
      TZ: America/Bogota
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d techtest"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: tecnica-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: techtest-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
